name: Package and Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: publish
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
        env:
          envFile: .env
      - name: copy readme
        run: cp README.md projects/arweave-wallet-kit-ng
      - name: install dependencies
        run: yarn
      - name: build
        run: yarn build
      - name: publish
        run: cd dist/arweave-wallet-kit-ng && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}